FROM ruby:2.7.1

RUN apt-get update && apt-get install -y nodejs
WORKDIR /app
COPY ./Gemfile* ./
RUN bundle install
COPY ./ ./

ENV JSON_VAR=$JSON_VAR

ENTRYPOINT ["./entrypoint.sh"]

EXPOSE 4000

CMD ["bundle", "exec", "sidekiq", "-c", "5", "-q", "default", "-q", "mailers", "-v"]
