name: Deploy From Github To AWS

on:
  push:
    branches: [staging, main]
  pull_request:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Ulearn backend docker image
        if: ${{ github.base_ref == 'staging' || github.ref == 'refs/heads/staging' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caleb42/u-learn-ruby-backend-staging:${{ github.sha }},caleb42/u-learn-ruby-backend-staging:latest
      - name: Build Ulearn backend docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caleb42/u-learn-ruby-backend-production:${{ github.sha }},caleb42/u-learn-ruby-backend-production:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy App to AWS
        if: ${{ github.base_ref == 'staging' || github.ref == 'refs/heads/staging' }}
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: LOperateur
          repo: ulearn-nginx-proxy
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: staging.yml
          ref: staging
          client_payload: '{"triggered": "true", "tag": "${{ github.sha }}", "container": "ulearn-backend", "queue": "sidekiq"}'
      - name: Deploy App to AWS
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: LOperateur
          repo: ulearn-nginx-proxy
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: staging.yml
          ref: main
          client_payload: '{"triggered": "true", "tag": "${{ github.sha }}", "container": "ulearn-backend", "queue": "sidekiq"}'
