name: Deploy From Github To AWS

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caleb42/u-learn-ruby-backend:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy App to AWS
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: LOperateur
          repo: ulearn-nginx-proxy
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: staging.yml
          ref: staging
